pub mod birth;
pub mod birth_legitimacy;
pub mod culture;
pub mod family;
    mod lineage; pub use lineage::LineageStrictness;
pub mod nobility;
pub mod people;
    mod religion; pub use religion::Deity;
pub mod status;
pub mod wealth;